apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flagger
  namespace: istio-system
spec:
  interval: 1h0m0s
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
  interval: 1h0m0s
  values:
    meshProvider: istio
    prometheus:
      install: false
    msteams:
      url: https://cdmsmisch.webhook.office.com/webhookb2/1e55a9d7-c21a-4dc1-b45a-12d95321c129@69be409d-5f67-4e5e-93c0-45a6600fde89/IncomingWebhook/39f273df556f4fe2861f2da692ca6cbf/5a7e750e-493f-495d-bc67-abbb3a9a95a8
    serviceAccount:
      create: true
      name: "flagger"

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-grafana
  namespace: istio-system
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: flagger
  interval: 1h0m0s
  releaseName: flagger-grafana
  values:
    url: http://flagger-prometheus.istio-system:9090
