apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: istio
  name: prometheus-community
spec:
  interval: 120m
  url: https://prometheus-community.github.io/helm-charts