apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-system
  namespace: monitoring
spec:
  interval: 10m0s
  path: ./monitoring
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
