apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-system-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:restricted
subjects:
- kind: ServiceAccount
  name: source-controller
  namespace: flux-system
- kind: ServiceAccount
  name: notification-controller
  namespace: flux-system
- kind: ServiceAccount
  name: image-automation-controller
  namespace: flux-system
- kind: ServiceAccount
  name: image-reflector-controller
  namespace: flux-system
- kind: ServiceAccount
  name: kyverno-service-account
  namespace: kyverno
- kind: ServiceAccount
  name: flagger-prometheus
  namespace: istio-system
- kind: ServiceAccount
  name: flagger-prometheus
  namespace: istio-system
- kind: ServiceAccount
  name: flagger-prometheus
  namespace: istio-system
- kind: ServiceAccount
  name: flagger-prometheus
  namespace: istio-system
- kind: ServiceAccount
  name: flagger
  namespace: istio-system
- kind: ServiceAccount
  name: istio-reader-service-account
  namespace: istio-system
- kind: ServiceAccount
  name: istiod-service-account
  namespace: istio-system
- kind: ServiceAccount
  name: istiod
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cdm::tenant-full-access
rules:
- apiGroups: ["", "extensions", "apps", "services", "configmaps", "secrets", "rbac.authorization.k8s.io"]
  resources: ["deployments", "replicasets", "pods", "services", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
